[tool.poetry]
name = "platonic"
version = "0.1.0"
description = "Package for recognizing registration plates"
authors = [
    "Szymon Cader <szymon.sc.cader@gmail.com>",
    "Patryk Kawa <kawapatryk99@gmail.com>",
    "Bartosz Rudnicki <bartek@rudnicki.szczecin.pl>"
]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
mkdocs = "^1.1.2"
markdown-include = "^0.6.0"
pytest = "^6.1.2"
pytest-cov = "^2.10.1"
flake8 = "^3.8.4"
tox = "^3.20.1"

[tool.poetry.scripts]
platonic = 'platonic.cli:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
